% -------------------------------------------------------------
%                  VTD_landscape_model_nosignal_v1 jacobian
% -------------------------------------------------------------
% generated by change_model_for_jacobian on 06-Jun-2019 10:30:00



function jac = VTD_landscape_model_nosignal_v1_jac(t,y,p)

%Model jacobian dy/dy

jac = [
     [ (p(12)*(3*y(2)^2 - 12*y(1)^2 + 2))  (-p(12)*(p(11) - 6*y(1)*y(2))) ];
     [ (-p(12)*(p(11) - 6*y(1)*y(2)))  (p(12)*(3*y(1)^2 - 12*y(2)^2)) ];
];

